Repository Harshdev098/Research-Nexas, pull requests merged in 2024-10, with the labels that each got.

#58 Refactor: Move Hardcoded Credentials to .env File
  file_upload/form_db.js
  file_upload/upload.js
Labels: hacktoberfest, gssoc-ext, level1, hacktoberfest-accepted

#93 Issue #84
  dashboard.html
Labels: hacktoberfest, gssoc-ext, level1, hacktoberfest-accepted

#212 Enhance the top services section
  public/css/style.css
Labels: hacktoberfest, gssoc-ext, level2, hacktoberfest-accepted

#282 fix: follow-us section in Student's main page
  public/css/main_page_style.css
Labels: hacktoberfest, gssoc-ext, level3, hacktoberfest-accepted

#315 Fixed Misalignment Between FAQs and Research Papers Sections on Homepage
  public/css/style.css
Labels: hacktoberfest, gssoc-ext, level1, hacktoberfest-accepted
